purge_on_cache_clear: true
storage: profiler.file_storage
exclude: ''
active_toolbar_items:
  assets: '0'
  blocks: '0'
  cache: '0'
  config: '0'
  database: '0'
  devel: '0'
  events: '0'
  drupal_extension: '0'
  forms: '0'
  http: '0'
  mail: '0'
  php_config: '0'
  performance_timing: '0'
  request: '0'
  routing: '0'
  services: '0'
  state: '0'
  theme: '0'
  time: '0'
  user: '0'
  views: '0'
ide_link: ''
ide_link_remote: ''
ide_link_local: ''
query_sort: null
query_highlight: null
